// src/components/ExitConfirm.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { getCurrentWindow } from '@tauri-apps/api/window'
import { listen, type UnlistenFn } from '@tauri-apps/api/event'

const appWindow = getCurrentWindow()
const showConfirm = ref(false)
const rememberChoice = ref(false)
let unlistenClose: UnlistenFn;

onMounted(async () => {
  // 🚀 监听全局事件
  unlistenClose = await listen<string>('request-close', (event) => {
    console.log("收到关闭信号:", event.payload);
    
    // 检查用户是否有“记住选择”
    const saved = localStorage.getItem('exit-preference');
    if (saved === 'minimize') {
      appWindow.hide();
    } else if (saved === 'quit') {
      appWindow.destroy();
    } else {
      showConfirm.value = true;
    }
  });
});

onUnmounted(() => {
  if (unlistenClose) unlistenClose();
});

const handleExit = async (action: 'minimize' | 'quit') => {
  if (rememberChoice.value) {
    localStorage.setItem('exit-preference', action);
  }

  if (action === 'minimize') {
    await appWindow.hide();
  } else {
    await appWindow.destroy(); // 彻底销毁进程
  }
  showConfirm.value = false;
};
</script>

<template>
  <Transition name="fade">
    <div v-if="showConfirm" class="fixed inset-0 z-[1000] flex items-center justify-center bg-black/80 backdrop-blur-md">
      <div class="glass-panel p-10 rounded-[2.5rem] border border-white/10 w-full max-w-sm shadow-2xl text-center space-y-8">
        <div class="space-y-2">
          <h2 class="text-xl font-bold text-amber-50">确认退出程序？</h2>
          <p class="text-xs text-zinc-500 leading-relaxed px-4">
            SafeMask 可以在后台继续保护您的剪贴板隐私。建议选择“最小化至托盘”。
          </p>
        </div>

        <div class="flex flex-col gap-3">
          <button @click="handleExit('minimize')" class="btn-exit-primary">
            最小化到系统托盘
          </button>
          <button @click="handleExit('quit')" class="btn-exit-secondary">
            彻底关闭程序
          </button>
        </div>

        <label class="flex items-center justify-center gap-2 cursor-pointer group">
          <input type="checkbox" v-model="rememberChoice" class="opacity-0 absolute">
          <div class="w-4 h-4 rounded border border-white/10 flex items-center justify-center transition-colors" :class="rememberChoice ? 'bg-amber-500 border-amber-500' : 'bg-black/40'">
             <div v-if="rememberChoice" class="w-2 h-2 bg-black rounded-sm"></div>
          </div>
          <span class="text-[10px] font-bold text-zinc-600 group-hover:text-zinc-400 transition-colors">记住我的选择</span>
        </label>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.glass-panel { background: rgba(15, 15, 20, 0.95); }
.btn-exit-primary { @apply w-full py-4 bg-amber-500 text-black rounded-2xl font-bold text-xs hover:bg-amber-400 active:scale-95 transition-all shadow-lg shadow-amber-500/10; }
.btn-exit-secondary { @apply w-full py-4 bg-white/5 border border-white/10 text-zinc-400 rounded-2xl font-bold text-xs hover:bg-white/10 hover:text-white transition-all; }
.fade-enter-active, .fade-leave-active { transition: opacity 0.3s ease; }
.fade-enter-from, .fade-leave-to { opacity: 0; }
</style>

// src/components/overlay/ExitConfirm.tsx
import { useState, useEffect } from "react";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { cn } from "@/lib/utils";

const STORAGE_KEY = "exit-preference";

export default function ExitConfirm() {
  const [visible, setVisible] = useState(false);
  const [rememberChoice, setRememberChoice] = useState(false);

  useEffect(() => {
    const appWindow = getCurrentWindow();

    const unlisten = appWindow.onCloseRequested(async (event) => {
      const preference = localStorage.getItem(STORAGE_KEY);

      if (preference === "minimize") {
        await appWindow.hide();
        return;
      }

      if (preference === "quit") {
        appWindow.destroy();
        return;
      }

      event.preventDefault();
      setVisible(true);
    });

    return () => {
      unlisten.then((fn) => fn());
    };
  }, []);

  const handleExit = async (action: "minimize" | "quit") => {
    const appWindow = getCurrentWindow();

    if (rememberChoice) {
      localStorage.setItem(STORAGE_KEY, action);
    }

    setVisible(false);

    if (action === "minimize") {
      await appWindow.hide();
    } else {
      appWindow.destroy();
    }
  };

  if (!visible) return null;

  return (
    <div
      className="fixed inset-0 z-[1000] flex items-center justify-center bg-black/80 backdrop-blur-md modal-backdrop"
      onClick={() => setVisible(false)}
    >
      <div
        className="p-12 rounded-4xl border border-white/10 w-full max-w-md shadow-2xl text-center space-y-8 bg-[#0f0f14]/95 modal-panel"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="space-y-2">
          <h2 className="text-2xl font-bold text-white">确认退出程序？</h2>
          <p className="text-base text-zinc-400 leading-relaxed">
            建议最小化到系统托盘
            <br />
            程序将在后台持续守护您的隐私数据
          </p>
        </div>

        <div className="space-y-3">
          <button
            type="button"
            onClick={() => handleExit("minimize")}
            className="w-full py-5 bg-amber-500 text-black rounded-2xl font-bold text-sm hover:bg-amber-400 active:scale-95 transition-all shadow-lg shadow-amber-500/10"
          >
            最小化到系统托盘
          </button>

          <button
            type="button"
            onClick={() => handleExit("quit")}
            className="w-full py-5 bg-white/5 border border-white/10 text-zinc-400 rounded-2xl font-bold text-sm hover:bg-white/10 hover:text-white transition-all"
          >
            彻底关闭程序
          </button>
        </div>

        <label className="flex items-center justify-center gap-2 cursor-pointer select-none">
          <input
            type="checkbox"
            checked={rememberChoice}
            onChange={(e) => setRememberChoice(e.target.checked)}
            className="w-4 h-4 rounded border-zinc-600 bg-zinc-800 text-amber-500 focus:ring-amber-500/30 focus:ring-offset-0 cursor-pointer"
          />
          <span className="text-sm text-zinc-500">记住我的选择</span>
        </label>
      </div>
    </div>
  );
}
