// src/components/RuleManager.vue
<script setup lang="ts">
import { ref, onMounted, computed, watch } from 'vue';
import { useAppStore } from '../stores/useAppStore';
import { MaskAPI } from '../services/api';
import { 
  Plus, Layers, Trash2, ShieldCheck, Search, Edit3, X, 
  Beaker, Check, AlertTriangle, Save, CopyPlus, Lock, Info
} from 'lucide-vue-next';
import { confirm, message } from '@tauri-apps/plugin-dialog';

const store = useAppStore();

// --- 状态管理 ---
const isSubmitting = ref(false);
const searchQuery = ref("");
const selectedRuleName = ref(""); // 标记当前选中的原始规则名

// --- 表单模型 ---
const initialForm = { name: '', pattern: '', mask: '<LABEL>', priority: 10, is_custom: true, enabled: true };
const form = ref({ ...initialForm });

// --- 实时验证逻辑 ---
const nameDuplicateError = computed(() => {
  if (!form.value.name) return "";
  const exists = store.allRulesList.find(r => r.name === form.value.name);
  if (exists) {
    if (selectedRuleName.value === exists.name && exists.is_custom) return ""; 
    return `库中已存在名为 [${form.value.name}] 的${exists.is_custom ? '自定义' : '系统'}规则`;
  }
  return "";
});

const patternDuplicateError = computed(() => {
  if (!form.value.pattern) return "";
  const exists = store.allRulesList.find(r => r.pattern === form.value.pattern);
  if (exists) {
    if (selectedRuleName.value === exists.name) return ""; 
    return `该表达式与规则 [${exists.name}] 重复`;
  }
  return "";
});

// --- 调试沙盒状态 ---
const testInput = ref(""); 
const testOutput = ref("");
const testError = ref("");

// 监听变动实时测试
watch([() => form.value.pattern, () => form.value.mask, testInput], async () => {
  if (!form.value.pattern || !testInput.value) { 
    testOutput.value = ""; 
    testError.value = "";
    return; 
  }
  try {
    testOutput.value = await MaskAPI.testRule(form.value.pattern, form.value.mask, testInput.value);
    testError.value = "";
  } catch (e: any) {
    testError.value = e.toString();
  }
}, { immediate: true });

onMounted(() => store.fetchAllRules());

// --- 核心交互方法 ---

const selectRule = (rule: any) => {
  selectedRuleName.value = rule.name;
  form.value = { ...rule };
};

const clearForm = () => {
  if (!selectedRuleName.value && form.value.name === "") return;
  selectedRuleName.value = "";
  form.value = { ...initialForm };
};

const handleSave = async (asNew = false) => {
  if (!form.value.name || !form.value.pattern) {
    await message("请填写完整的规则名称和正则表达式", { title: "数据缺失", kind: "warning" });
    return;
  }

  if (asNew) {
    const isDuplicate = store.allRulesList.some(r => r.name === form.value.name || r.pattern === form.value.pattern);
    if (isDuplicate) {
      await message("检测到规则库中已存在相同名称或表达式的记录，请修改后再保存。", { title: "拒绝重复添加", kind: "error" });
      return;
    }
  }

  isSubmitting.value = true;
  try {
    const payload = { ...form.value };
    if (asNew) payload.is_custom = true;

    await MaskAPI.saveRule(payload);
    await store.fetchAllRules();
    await store.fetchStats();
    
    if (asNew) selectedRuleName.value = payload.name;
    await message(asNew ? "规则已作为新模式存入库中" : "规则修改已即时应用至脱敏引擎", { title: "注入成功", kind: "info" });
  } catch (e) {
    await message("引擎注入失败: " + e, { kind: "error" });
  } finally {
    isSubmitting.value = false;
  }
};

const handleDelete = async (name: string) => {
  const ok = await confirm(`此操作将永久删除自定义规则 [${name}]。确定继续吗？`, { title: '销毁确认', kind: 'warning' });
  if (ok) {
    await MaskAPI.deleteRule(name);
    await store.fetchAllRules();
    await store.fetchStats();
    if (selectedRuleName.value === name) clearForm();
  }
};

const sortedRules = computed(() => {
  let f = store.allRulesList;
  if (searchQuery.value) {
    const q = searchQuery.value.toLowerCase();
    f = f.filter(r => r.name.toLowerCase().includes(q) || r.pattern.toLowerCase().includes(q));
  }
  return [...f].sort((a, b) => (a.is_custom === b.is_custom ? b.priority - a.priority : a.is_custom ? -1 : 1));
});
</script>

<template>
  <div class="flex items-stretch gap-6 h-full overflow-hidden animate-in fade-in duration-700" @click="clearForm">
    
    <!-- 1. 左侧：规则列表面板 -->
    <div class="flex-1 min-w-0 flex flex-col bg-[#0d0d0f]/60 border border-white/[0.04] rounded-[2rem] overflow-hidden" @click.stop>
      <div class="px-8 py-5 border-b border-white/[0.04] flex items-center justify-between">
        <div class="flex items-center gap-3">
          <Layers :size="18" class="text-amber-500/50" />
          <h3 class="font-bold text-amber-50/80 text-sm tracking-widest uppercase">规则模式库</h3>
        </div>
        <div class="relative group">
          <Search class="absolute left-3 top-1/2 -translate-y-1/2 text-zinc-600 group-focus-within:text-amber-500/40 transition-colors" :size="14" />
          <input v-model="searchQuery" placeholder="快速检索模式..." class="search-bar" />
        </div>
      </div>
      
      <div class="flex-1 overflow-y-auto p-5 space-y-2 custom-scroll" @click.self="clearForm">
        <div v-for="rule in sortedRules" :key="rule.name" 
             @click.stop="selectRule(rule)"
             class="rule-item group" 
             :class="{ 'active': selectedRuleName === rule.name }">
          
          <div class="flex-1 min-w-0 pr-4">
            <div class="flex items-center gap-2 mb-0.5">
              <span class="text-sm font-bold truncate text-zinc-200">{{ rule.name }}</span>
              <span :class="rule.is_custom ? 'tag-custom' : 'tag-system'">
                {{ rule.is_custom ? 'Custom' : 'System' }}
              </span>
            </div>
            <code class="pattern-text">{{ rule.pattern }}</code>
          </div>

          <div class="flex items-center gap-3 shrink-0">
            <span class="mask-label">{{ rule.mask }}</span>
            <div class="w-6 flex justify-center">
              <button v-if="rule.is_custom" @click.stop="handleDelete(rule.name)" 
                      class="delete-trigger">
                <Trash2 :size="14" />
              </button>
              <ShieldCheck v-else :size="14" class="text-zinc-800" />
            </div>
          </div>
        </div>
        <div class="flex-1 min-h-[120px]" @click.self="clearForm"></div>
      </div>
    </div>

    <!-- 2. 右侧：配置区域 -->
    <div class="w-[420px] flex flex-col gap-5 overflow-y-auto custom-scroll pr-1" @click.stop>
      
      <div class="glass-panel p-8 space-y-7 shadow-2xl">
        <div class="flex justify-between items-center">
          <div class="flex items-center gap-4">
            <div class="w-10 h-10 rounded-xl bg-white/[0.03] border border-white/10 flex items-center justify-center">
              <Edit3 v-if="selectedRuleName" :size="18" class="text-amber-400" />
              <Plus v-else :size="18" class="text-blue-500" />
            </div>
            <h3 class="font-bold text-amber-50/90 tracking-tight">{{ selectedRuleName ? '配置既有模式' : '创建新脱敏模式' }}</h3>
          </div>
          <button v-if="selectedRuleName" @click.stop="clearForm" class="text-zinc-600 hover:text-white transition-all" title="切换回新建模式">
            <Plus :size="18" />
          </button>
        </div>

        <div v-if="!form.is_custom && selectedRuleName" class="bg-amber-900/10 border border-amber-500/20 p-4 rounded-2xl flex gap-4 animate-in slide-in-from-top-2">
           <Lock :size="20" class="text-amber-500 shrink-0 mt-0.5" />
           <p class="text-[11px] text-amber-200/50 leading-relaxed font-medium">
             系统预设模式不可直接覆盖。请修改参数后使用下方“另存为”功能创建副本。
           </p>
        </div>

        <div class="space-y-6" :class="{ 'opacity-30 pointer-events-none filter grayscale': !form.is_custom && selectedRuleName }">
          <div class="input-group">
            <div class="label-header"><label>规则显示名称</label><span class="required-dot"></span></div>
            <div class="input-wrapper">
              <input v-model="form.name" placeholder="例如：用户隐私手机号" />
            </div>
            <p v-if="nameDuplicateError" class="validation-msg"><Info :size="10" /> {{ nameDuplicateError }}</p>
          </div>

          <div class="input-group">
            <div class="label-header"><label>正则表达式 (RUST REGEX)</label><span class="required-dot"></span></div>
            <div class="input-wrapper">
              <textarea v-model="form.pattern" class="h-28 font-mono text-[12px]" placeholder="输入匹配模式..." />
            </div>
            <p v-if="patternDuplicateError" class="validation-msg"><Info :size="10" /> {{ patternDuplicateError }}</p>
          </div>

          <div class="grid grid-cols-2 gap-5">
            <div class="input-group">
              <div class="label-header"><label>脱敏掩码标签</label></div>
              <div class="input-wrapper">
                <input v-model="form.mask" class="text-center text-blue-400 font-mono font-bold tracking-widest" />
              </div>
            </div>
            <div class="input-group">
              <div class="label-header"><label>注入权重 (优先级)</label></div>
              <div class="input-wrapper">
                <input type="number" v-model.number="form.priority" class="text-center font-mono" />
              </div>
            </div>
          </div>
        </div>

        <div class="flex flex-col gap-3 pt-4">
          <button v-if="form.is_custom && selectedRuleName" @click="handleSave(false)" 
                  class="btn-primary" :disabled="isSubmitting || !!nameDuplicateError">
            <Save :size="16" /> 保存修改
          </button>
          <button v-if="!selectedRuleName" @click="handleSave(false)" 
                  class="btn-primary" :disabled="isSubmitting || !!nameDuplicateError">
            <Plus :size="16" /> 注入脱敏引擎
          </button>
          <button v-if="selectedRuleName" @click="handleSave(true)" 
                  class="btn-secondary" :disabled="isSubmitting">
            <CopyPlus :size="16" /> 另存为自定义规则
          </button>
        </div>
      </div>

      <!-- 调试沙盒 -->
      <div class="glass-panel p-8 flex-1 border-emerald-500/10">
        <div class="flex items-center gap-3 mb-6">
          <div class="p-1.5 bg-emerald-500/10 rounded-lg"><Beaker :size="16" class="text-emerald-400" /></div>
          <h3 class="font-bold text-amber-50/80">调试沙盒</h3>
        </div>

        <div class="space-y-4">
          <div class="relative">
            <span class="sandbox-label">Test Input</span>
            <textarea v-model="testInput" placeholder="在这里输入原始文本进行测试..." class="sandbox-area input custom-scroll" />
          </div>
          <div class="relative">
            <span class="sandbox-label" :class="testError ? 'text-red-500' : 'text-emerald-500'">
              {{ testError ? '正则语法错误' : '实时预览' }}
            </span>
            <div class="sandbox-area output custom-scroll" :class="{'err': testError}">
              <span v-if="testError" class="text-red-400 font-mono text-[10px] leading-tight">{{ testError }}</span>
              <span v-else class="text-emerald-100/70">{{ testOutput }}</span>
              <Check v-if="!testError && testOutput !== testInput && testInput" class="absolute right-3 bottom-3 text-emerald-500/40" :size="16" />
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</template>

<style scoped>
/* --- 列表与通用项 --- */
.search-bar { @apply bg-black/40 border border-amber-500/10 rounded-xl py-2 pl-9 pr-4 text-xs text-amber-50/80 outline-none focus:border-amber-500/40 transition-all w-48 focus:w-64; }
.rule-item { @apply flex items-center p-4 rounded-2xl bg-white/[0.01] border border-white/[0.03] transition-all cursor-pointer relative overflow-hidden; }
.rule-item:hover { @apply bg-white/[0.03] border-white/[0.08] translate-x-1; }
.rule-item.active { @apply border-amber-500/30 bg-amber-500/[0.04] shadow-[0_10px_30px_rgba(0,0,0,0.4)]; }
.rule-item.active::before { content: ''; @apply absolute left-0 top-3 bottom-3 w-[2px] bg-amber-500 rounded-full; }
.pattern-text { @apply text-[10px] font-mono text-zinc-600 truncate block whitespace-nowrap overflow-hidden; max-width: 280px; }
.tag-custom { @apply text-[8px] bg-blue-500/10 text-blue-400 border border-blue-500/20 px-1.5 py-0.5 rounded font-black uppercase; }
.tag-system { @apply text-[8px] bg-zinc-800 text-zinc-500 border border-white/5 px-1.5 py-0.5 rounded font-black uppercase; }
.mask-label { @apply text-[9px] font-mono font-bold text-emerald-400/70 bg-emerald-500/5 px-2.5 py-1 rounded-lg border border-emerald-500/10; }
.delete-trigger { @apply p-1.5 rounded-lg text-zinc-700 hover:text-red-400 hover:bg-red-500/10 transition-all opacity-0 group-hover:opacity-100; }

/* --- 🚀 输入表单优化核心 --- */
.input-group { @apply flex flex-col gap-2.5 relative; }
.label-header { @apply flex items-center justify-between px-1.5; }
.label-header label {
  /* 🚀 提升 Label 辨识度：微黄象牙白 */
  @apply text-[11px] font-bold text-amber-100/80 uppercase tracking-[0.12em];
}
.required-dot { @apply w-1.5 h-1.5 rounded-full bg-amber-500/60 shadow-[0_0_8px_rgba(245,158,11,0.3)]; }

.input-wrapper {
  /* 🚀 修复点：使用方括号语法处理任意不透明度 */
  @apply relative rounded-xl bg-[#08080a] border border-white/[0.12] transition-all duration-300 shadow-inner;
}
.input-wrapper:hover { @apply border-white/[0.2]; }
.input-wrapper:focus-within {
  @apply border-amber-500/40 bg-[#0a0a0c];
  box-shadow: 0 0 20px rgba(245, 158, 11, 0.05), inset 0 2px 10px rgba(0, 0, 0, 0.6);
}
.input-wrapper input, .input-wrapper textarea {
  @apply w-full bg-transparent border-none outline-none p-3.5 text-[13px] text-amber-50/90 placeholder:text-zinc-800 transition-all font-medium;
}

.validation-msg { @apply text-[10px] text-amber-400 font-bold mt-1.5 flex items-center gap-1.5 px-2; }

/* --- 按钮与面板 --- */
.btn-primary { @apply w-full py-4 bg-amber-500/10 border border-amber-500/30 text-amber-500 rounded-2xl font-black uppercase tracking-widest text-[11px] flex items-center justify-center gap-3 hover:bg-amber-500 hover:text-black transition-all active:scale-[0.97]; }
.btn-secondary { @apply w-full py-3.5 bg-zinc-900 border border-white/5 text-zinc-500 rounded-2xl text-[10px] font-black uppercase tracking-widest flex items-center justify-center gap-3 hover:text-amber-200 hover:border-amber-500/20 transition-all; }

.glass-panel { @apply bg-[#0d0d0f]/80 border border-white/[0.04] rounded-[2.5rem]; }
.sandbox-label { @apply text-[9px] font-bold uppercase tracking-widest absolute -top-2.5 left-5 px-2 bg-[#0c0b0a] z-10 text-amber-100/60; }
.sandbox-area { @apply w-full bg-black/40 border border-white/[0.1] rounded-2xl p-4 text-[12px] font-mono leading-relaxed outline-none transition-all resize-none; }
.sandbox-area.input:focus { @apply border-amber-500/30; }
.sandbox-area.output { @apply min-h-[100px] bg-emerald-500/[0.01] border-emerald-500/10; }

.custom-scroll::-webkit-scrollbar { width: 2px; }
.custom-scroll::-webkit-scrollbar-thumb { @apply bg-amber-500/10 rounded-full; }
</style>

// src/components/rules/RuleManager.tsx
import { useState, useEffect, useMemo, useCallback } from "react";
import { motion } from "framer-motion";
import {
  Plus, Layers, Trash2, ShieldCheck, Search, Edit3, X,
  Beaker, Check, Save, CopyPlus, Lock, Info, Fingerprint,
} from "lucide-react";
import { useAppStore } from "@/hooks/useAppStore";
import { MaskAPI, type Rule } from "@/services/api";
import { cn } from "@/lib/utils";

// ───────────────────────────────────────────────────────────────────────────────
// Types
// ───────────────────────────────────────────────────────────────────────────────

interface FormState {
  name: string;
  pattern: string;
  mask: string;
  priority: number;
  is_custom: boolean;
  enabled: boolean;
}

interface ValidationErrors {
  nameDuplicate?: string;
  patternDuplicate?: string;
}

// ───────────────────────────────────────────────────────────────────────────────
// Helpers
// ───────────────────────────────────────────────────────────────────────────────

const EMPTY_FORM: FormState = {
  name: "",
  pattern: "",
  mask: "<LABEL>",
  priority: 10,
  is_custom: true,
  enabled: true,
};

/** Convert a Rule into the form state shape. */
function ruleToForm(r: Rule): FormState {
  return {
    name: r.name,
    pattern: r.pattern,
    mask: r.mask,
    priority: r.priority,
    is_custom: r.is_custom,
    enabled: r.enabled,
  };
}

/** Convert form state + is_custom override into a Rule payload. */
function formToRule(form: FormState, isCustom: boolean): Rule {
  return {
    name: form.name,
    pattern: form.pattern,
    mask: form.mask,
    priority: Number(form.priority),
    is_custom: isCustom,
    enabled: form.enabled,
  };
}

// ───────────────────────────────────────────────────────────────────────────────
// Component
// ───────────────────────────────────────────────────────────────────────────────

export default function RuleManager() {
  // --- Store ---
  const allRules = useAppStore((s) => s.allRulesList);
  const fetchAllRules = useAppStore((s) => s.fetchAllRules);
  const fetchStats = useAppStore((s) => s.fetchStats);

  // --- Local state ---
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedName, setSelectedName] = useState<string | null>(null);
  const [showBadge, setShowBadge] = useState(true);

  // Form
  const [form, setForm] = useState<FormState>(EMPTY_FORM);
  const [validationErrors, setValidationErrors] = useState<ValidationErrors>({});

  // Sandbox
  const [testInput, setTestInput] = useState("");
  const [testOutput, setTestOutput] = useState("");
  const [testError, setTestError] = useState("");

  // ── Derived ──

  const isEditing = selectedName !== null;
  const selectedRule = useMemo(
    () => allRules.find((r) => r.name === selectedName) ?? null,
    [allRules, selectedName],
  );
  const isSystemRule = isEditing && selectedRule && !selectedRule.is_custom;

  // Sorted + filtered rules
  const sortedRules = useMemo(() => {
    let list = [...allRules];

    // Search filter
    if (searchQuery) {
      const q = searchQuery.toLowerCase();
      list = list.filter(
        (r) =>
          r.name.toLowerCase().includes(q) ||
          r.pattern.toLowerCase().includes(q),
      );
    }

    // Sort: custom first, then by priority desc
    list.sort((a, b) => {
      if (a.is_custom !== b.is_custom) return a.is_custom ? -1 : 1;
      return b.priority - a.priority;
    });

    return list;
  }, [allRules, searchQuery]);

  // ── Form handlers ──

  const updateForm = useCallback((patch: Partial<FormState>) => {
    setForm((prev) => ({ ...prev, ...patch }));
    // Clear duplicate errors when user edits the field
    setValidationErrors((prev) => {
      const next = { ...prev };
      if (patch.name !== undefined) delete next.nameDuplicate;
      if (patch.pattern !== undefined) delete next.patternDuplicate;
      return next;
    });
  }, []);

  const selectRule = useCallback((rule: Rule) => {
    setSelectedName(rule.name);
    setForm(ruleToForm(rule));
    setValidationErrors({});
    setTestOutput("");
    setTestError("");
  }, []);

  const clearForm = useCallback(() => {
    setSelectedName(null);
    setForm(EMPTY_FORM);
    setValidationErrors({});
    setTestOutput("");
    setTestError("");
  }, []);

  // ── Validation ──

  const validate = useCallback(
    (name: string, pattern: string): boolean => {
      const errs: ValidationErrors = {};

      if (!name.trim()) {
        errs.nameDuplicate = "Rule name is required";
      } else {
        // Check name duplicate (exclude self when editing)
        const dupName = allRules.find(
          (r) => r.name === name && r.name !== selectedName,
        );
        if (dupName) errs.nameDuplicate = `Rule "${name}" already exists`;
      }

      if (!pattern.trim()) {
        errs.patternDuplicate = "Pattern cannot be empty";
      } else {
        // Check pattern duplicate
        const dupPattern = allRules.find(
          (r) => r.pattern === pattern && r.name !== selectedName,
        );
        if (dupPattern)
          errs.patternDuplicate = `Pattern already used by "${dupPattern.name}"`;
      }

      setValidationErrors(errs);
      return Object.keys(errs).length === 0;
    },
    [allRules, selectedName],
  );

  // ── CRUD handlers ──

  const handleSave = useCallback(
    async (asNew: boolean) => {
      const targetName = asNew ? form.name : form.name;
      const targetPattern = form.pattern;

      if (!validate(targetName, targetPattern)) return;

      try {
        // When saving as new or editing a system rule, override is_custom = true
        const isCustom = Boolean(asNew || isSystemRule);
        await MaskAPI.saveRule(formToRule(form, isCustom));
        await Promise.all([fetchAllRules(), fetchStats()]);

        if (asNew || isSystemRule) {
          // After saving as copy, select the new rule
          setSelectedName(form.name);
        }

        setShowBadge(true);
        setTimeout(() => setShowBadge(false), 2000);
      } catch (e) {
        console.error("Save rule error:", e);
      }
    },
    [form, validate, isSystemRule, fetchAllRules, fetchStats],
  );

  const handleDelete = useCallback(
    async (name: string) => {
      try {
        // Confirm dialog
        await MaskAPI.deleteRule(name);
        if (selectedName === name) clearForm();
        await Promise.all([fetchAllRules(), fetchStats()]);
      } catch (e) {
        console.error("Delete rule error:", e);
      }
    },
    [selectedName, clearForm, fetchAllRules, fetchStats],
  );

  // ── Sandbox ──

  useEffect(() => {
    // Debounce: only run when the user has actually typed something
    const hasPattern = form.pattern.trim().length > 0;
    const hasText = testInput.trim().length > 0;

    if (!hasPattern || !hasText) {
      setTestOutput("");
      setTestError("");
      return;
    }

    let cancelled = false;
    const timer = setTimeout(async () => {
      try {
        const result = await MaskAPI.testRule(
          form.pattern,
          form.mask,
          testInput,
        );
        if (!cancelled) {
          setTestOutput(result);
          setTestError("");
        }
      } catch (e) {
        if (!cancelled) {
          setTestOutput("");
          setTestError(String(e));
        }
      }
    }, 300);

    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
  }, [form.pattern, form.mask, testInput]);

  // ── Initial data load ──

  useEffect(() => {
    fetchAllRules();
  }, [fetchAllRules]);

  // ── Render helpers ──

  const renderSearchBar = () => (
    <div className="relative">
      <Search
        size={13}
        className="absolute left-3.5 top-1/2 -translate-y-1/2 text-amber-500/30 pointer-events-none"
      />
      <input
        value={searchQuery}
        onChange={(e) => setSearchQuery(e.target.value)}
        placeholder="快速检索..."
        className="w-full bg-[#08080a] border border-amber-500/10 rounded-xl py-2.5 pl-10 pr-8 text-[11px] text-amber-50/80 outline-none transition-all duration-500 shadow-inner hover:border-white/20 focus:border-amber-500/40 focus:shadow-[0_0_15px_rgba(245,158,11,0.03),inset_0_2px_8px_rgba(0,0,0,0.6)]"
      />
    </div>
  );

  const renderRuleItem = (rule: Rule) => {
    const active = selectedName === rule.name;
    return (
      <div
        key={rule.name}
        onClick={() => selectRule(rule)}
        className={cn(
          "group flex items-center p-4 rounded-2xl bg-white/[0.01] border border-white/[0.03] transition-all cursor-pointer relative overflow-hidden hover:bg-white/[0.03] hover:border-white/[0.08] hover:translate-x-1",
          active &&
            "border-amber-500/30 bg-amber-500/[0.04] shadow-[0_10px_30px_rgba(0,0,0,0.4)]",
          active && "before:content-[''] before:absolute before:left-0 before:top-3 before:bottom-3 before:w-[2px] before:bg-amber-500 before:rounded-full",
        )}
      >
        {/* Left icon */}
        <div className="mr-3">
          {rule.is_custom ? (
            <Edit3 size={14} className="text-blue-400/60" />
          ) : (
            <Lock size={14} className="text-zinc-600" />
          )}
        </div>

        {/* Info */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-[13px] font-bold text-zinc-200 truncate">
              {rule.name}
            </span>
            <span
              className={cn(
                "text-[8px] border px-1.5 py-0.5 rounded font-black uppercase",
                rule.is_custom
                  ? "bg-blue-500/10 text-blue-400 border-blue-500/20"
                  : "bg-zinc-800 text-zinc-500 border-white/5",
              )}
            >
              {rule.is_custom ? "CUSTOM" : "SYSTEM"}
            </span>
          </div>
          <span className="text-[10px] font-mono text-zinc-600 truncate block whitespace-nowrap overflow-hidden max-w-[280px]">
            {rule.pattern}
          </span>
        </div>

        {/* Mask label */}
        <div className="mx-2 shrink-0">
          <span className="text-[9px] font-mono font-bold text-emerald-400/70 bg-emerald-500/5 px-2.5 py-1 rounded-lg border border-emerald-500/10">
            {rule.mask}
          </span>
        </div>

        {/* Delete button */}
        {rule.is_custom && (
          <button
            onClick={(e) => {
              e.stopPropagation();
              handleDelete(rule.name);
            }}
            className="p-1.5 rounded-lg text-zinc-700 hover:text-red-400 hover:bg-red-500/10 transition-all opacity-0 group-hover:opacity-100"
          >
            <Trash2 size={13} />
          </button>
        )}
      </div>
    );
  };

  const renderFormField = (
    label: string,
    field: keyof FormState,
    type: "input" | "textarea" | "number" = "input",
    extraClass = "",
  ) => {
    const value = form[field];
    const rows = type === "textarea" ? 28 : undefined;

    const inputElement =
      type === "textarea" ? (
        <textarea
          value={value as string}
          onChange={(e) => updateForm({ [field]: e.target.value })}
          rows={rows}
          className="w-full bg-transparent border-none outline-none p-3.5 text-[13px] text-amber-50/90 placeholder:text-zinc-800 font-medium resize-none"
          placeholder={
            field === "pattern"
              ? "正则表达式..."
              : field === "mask"
                ? "<LABEL>"
                : ""
          }
        />
      ) : (
        <input
          type={type === "number" ? "number" : "text"}
          value={value as string | number}
          onChange={(e) =>
            updateForm({
              [field]:
                type === "number"
                  ? Number(e.target.value)
                  : e.target.value,
            })
          }
          className={cn(
            "w-full bg-transparent border-none outline-none p-3.5 text-[13px] text-amber-50/90 placeholder:text-zinc-800 font-medium",
            type === "number" && "text-center",
          )}
          placeholder={field === "name" ? "脱敏规则名称" : ""}
        />
      );

    return (
      <div className="flex flex-col gap-2">
        <label className="text-[11px] font-bold text-amber-100/80 uppercase tracking-[0.12em]">
          {label}
        </label>
        <div
          className={cn(
            "relative rounded-xl bg-[#08080a] border border-white/[0.12] transition-all duration-300 shadow-inner hover:border-white/[0.2] focus-within:border-amber-500/40 focus-within:bg-[#0a0a0c] focus-within:shadow-[0_0_20px_rgba(245,158,11,0.05),inset_0_2px_10px_rgba(0,0,0,0.6)]",
            extraClass,
          )}
        >
          {inputElement}
        </div>

        {/* Validation messages */}
        {field === "name" && validationErrors.nameDuplicate && (
          <span className="text-[10px] text-amber-400 font-bold mt-1.5 flex items-center gap-1.5 px-2">
            <X size={10} />
            {validationErrors.nameDuplicate}
          </span>
        )}
        {field === "pattern" && validationErrors.patternDuplicate && (
          <span className="text-[10px] text-amber-400 font-bold mt-1.5 flex items-center gap-1.5 px-2">
            <X size={10} />
            {validationErrors.patternDuplicate}
          </span>
        )}
      </div>
    );
  };

  const renderSandbox = () => {
    const hasPattern = form.pattern.trim().length > 0;
    const hasText = testInput.trim().length > 0;
    const showOutput = hasPattern && hasText && !testError;
    const showStandby = !hasPattern || !hasText;

    return (
      <div className="relative">
        {/* Label */}
        <span className="text-[9px] font-bold uppercase tracking-widest absolute -top-2.5 left-5 px-2 bg-[#0c0b0a] z-10 text-amber-100/60">
          <div className="flex items-center gap-1.5">
            <Beaker size={10} className="text-amber-400/60" />
            调试沙盒实验室
          </div>
        </span>

        <div className="bg-[#0d0d0f]/60 border border-white/[0.08] rounded-[2rem] p-5 pt-8 space-y-4">
          {/* Input */}
          <textarea
            value={testInput}
            onChange={(e) => setTestInput(e.target.value)}
            placeholder="输入测试文本..."
            className="w-full bg-black/40 border border-white/[0.08] rounded-2xl p-5 text-[13px] font-mono leading-relaxed outline-none transition-all resize-none focus:border-amber-500/30 min-h-[80px] text-amber-50/70 placeholder:text-zinc-700"
          />

          {/* Output area */}
          <div
            className={cn(
              "w-full bg-black/40 border rounded-2xl p-5 text-[13px] font-mono leading-relaxed outline-none transition-all resize-none min-h-[100px]",
              showOutput &&
                "bg-emerald-500/[0.01] border-emerald-500/10 text-emerald-300/80",
              showStandby &&
                "border-dashed border-white/[0.06] bg-black/20 text-zinc-700",
              testError && "border-red-500/20 bg-red-500/[0.02] text-red-400",
            )}
          >
            {testError && (
              <div className="flex items-start gap-2">
                <X size={13} className="mt-0.5 shrink-0 text-red-400" />
                <span>{testError}</span>
              </div>
            )}

            {showOutput && (
              <div className="flex items-start gap-2">
                <Check size={13} className="mt-0.5 shrink-0 text-emerald-400" />
                <span className="whitespace-pre-wrap">{testOutput}</span>
              </div>
            )}

            {showStandby && !testError && (
              <div className="flex flex-col items-center justify-center py-6 text-center gap-3">
                <Fingerprint
                  size={24}
                  className="text-zinc-700/60"
                />
                <div>
                  <p className="text-zinc-600 font-bold text-[11px]">
                    Engine Standby
                  </p>
                  <p className="text-zinc-700 text-[10px] mt-1">
                    Enter a pattern and test text to see live masking results
                  </p>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    );
  };

  // ── Main render ──

  return (
    <div className="flex items-stretch gap-6 h-full overflow-hidden">
      {/* ── Left panel: Rule list ── */}
      <div className="flex-1 min-w-0 flex flex-col bg-[#0d0d0f]/60 border border-white/[0.04] rounded-[2rem] overflow-hidden">
        {/* Header */}
        <div className="px-8 py-6 border-b border-white/[0.04] flex items-center gap-6">
          <Layers size={16} className="text-amber-500/60" />
          <h3 className="font-black text-amber-50/90 text-[13px] uppercase tracking-[0.08em]">
            Pattern Repository
          </h3>
          <div className="flex-1">{renderSearchBar()}</div>
          <button
            onClick={clearForm}
            className="p-2 rounded-xl bg-amber-500/10 text-amber-400 hover:bg-amber-500/20 transition-all"
          >
            <Plus size={14} />
          </button>
        </div>

        {/* Rule list */}
        <div className="flex-1 overflow-y-auto p-5 space-y-3 custom-scroll">
          {sortedRules.map(renderRuleItem)}

          {sortedRules.length === 0 && (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <Fingerprint
                size={32}
                className="text-zinc-700/40 mb-4"
              />
              <p className="text-zinc-600 text-[12px] font-bold">
                {searchQuery
                  ? "No rules match your search"
                  : "No rules defined yet"}
              </p>
              <p className="text-zinc-700 text-[10px] mt-1">
                {searchQuery
                  ? "Try a different search term"
                  : "Click + to create your first rule"}
              </p>
            </div>
          )}
        </div>
      </div>

      {/* ── Right panel: Editor + Sandbox ── */}
      <div className="w-[420px] flex flex-col gap-5 overflow-y-auto custom-scroll pr-1">
        {/* Form container */}
        <div className="bg-[#0d0d0f]/80 border border-white/[0.04] rounded-[2.5rem] p-8 space-y-6 shadow-2xl">
          {/* Title */}
          <div className="flex items-center gap-3">
            <ShieldCheck
              size={16}
              className={cn(
                "transition-colors",
                isEditing ? "text-amber-400" : "text-zinc-600",
              )}
            />
            <h3 className="font-bold text-amber-50/90 text-[13px]">
              {isEditing ? "配置既有模式" : "创建新脱敏模式"}
            </h3>

            {/* Badge */}
            {showBadge && (
              <motion.span
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0 }}
                className="text-[8px] bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 px-1.5 py-0.5 rounded font-black uppercase ml-auto"
              >
                <div className="flex items-center gap-1">
                  <Check size={8} />
                  SAVED
                </div>
              </motion.span>
            )}
          </div>

          {/* Form fields */}
          {renderFormField("NAME", "name")}
          {renderFormField("PATTERN", "pattern", "textarea")}
          {renderFormField("MASK", "mask")}
          {renderFormField("PRIORITY", "priority", "number")}

          {/* System rule warning */}
          {isSystemRule && (
            <motion.div
              initial={{ opacity: 0, y: -4 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-amber-900/10 border border-amber-500/20 p-4 rounded-2xl flex gap-4"
            >
              <Info
                size={16}
                className="text-amber-400/70 shrink-0 mt-0.5"
              />
              <p className="text-[11px] text-amber-200/70 leading-relaxed">
                系统预设模式不可直接覆盖。请修改参数后使用下方"另存为"功能创建副本。
              </p>
            </motion.div>
          )}

          {/* Action buttons */}
          <div className="space-y-3 pt-2">
            {isEditing ? (
              <>
                <button
                  onClick={() => handleSave(false)}
                  className="w-full py-4 bg-amber-500/10 border border-amber-500/30 text-amber-500 rounded-2xl font-black uppercase tracking-widest text-[11px] flex items-center justify-center gap-3 hover:bg-amber-500 hover:text-black transition-all active:scale-[0.97]"
                >
                  <Save size={13} />
                  保存修改
                </button>
                <button
                  onClick={() => handleSave(true)}
                  className="w-full py-3.5 bg-zinc-900 border border-white/5 text-zinc-500 rounded-2xl text-[10px] font-black uppercase tracking-widest flex items-center justify-center gap-3 hover:text-amber-200 hover:border-amber-500/20 transition-all"
                >
                  <CopyPlus size={12} />
                  另存为自定义规则
                </button>
              </>
            ) : (
              <button
                onClick={() => handleSave(false)}
                disabled={!form.name.trim() || !form.pattern.trim()}
                className="w-full py-4 bg-amber-500/10 border border-amber-500/30 text-amber-500 rounded-2xl font-black uppercase tracking-widest text-[11px] flex items-center justify-center gap-3 hover:bg-amber-500 hover:text-black transition-all active:scale-[0.97] disabled:opacity-30 disabled:cursor-not-allowed disabled:hover:bg-amber-500/10 disabled:hover:text-amber-500"
              >
                <Save size={13} />
                注入脱敏引擎
              </button>
            )}
          </div>
        </div>

        {/* Sandbox */}
        {renderSandbox()}
      </div>
    </div>
  );
}
